### ISSUE TITLE
Improvements 

### ISSUE THREAD

**Issue by Manask322** [Manask322/BooleanService#4]
**TODO** 

- [x] Change directory structure.
- [x] Verify Authorization of Users
- [ ] Debug the queuing to database in Service Queue Implementation

- [x] Add Test Cases to cover more functions and corner cases 

- [ ] Look up and Implement proper Mutex locking (considering different pods)

- [x]  Give proper Error Message to the User
